### PR TITLE
Fix incorrect running head in Hochlehnert et al.

### PR DESCRIPTION
**Pull request by aterenin**
Hi all

This PR fixes an incorrect running head in Hochlehnert et al.

It used to show `Andreas Hochlehnert, Alexander Terenin` and it now shows `Andreas Hochlehnert, Alexander Terenin, Steindór Sæmondsson, and Marc Peter Deisenroth`.

There are no other changes.

### CODE REVIEW

**Comment by lawrennd** [comment]
Hi Alex,  We don’t normally accept new pdf files without confirmation from original conference editors that changes are OK. Can you confirm you have authorisation?

**Comment by aterenin** [comment]
Thanks Neil! I've pinged the publication chair for AISTATS 2021, @krikamol, to approve this

**Comment by krikamol** [comment]
@aterenin Could you please confirm that no other changes have been made in the paper?

**Comment by aterenin** [comment]
Confirming, everything else is identical - just the running head.

**Comment by krikamol** [comment]
@lawrennd Since the change is minor and provides more accurate attribution of the authors, I approve it. Thank you.

**Review by lawrennd — APPROVED** [review]
Approved as per conversation with Krikamol

**Pull request merged**
