### PR TITLE
Updated baseline results and a typo fix in borovitskiy21a

### PR DESCRIPTION
**Pull request by vabor112**
We have updated subsection 4.3 of the paper in accordance with the updated and extended baseline results that we obtained after fixing a baseline implementation bug that we [were made aware of](https://github.com/spbu-math-cs/Graph-Gaussian-Processes/issues/1) after the camera ready deadline. Also a small typo in the appendix was fixed.

### CODE REVIEW

**Review by lawrennd — COMMENTED** [review]
Thanks for submitting @vabor112 

I'm not sure how we're handling updates to Camera Readies yet ... but I've invited @krikamol to the repo with write access so that he can decide.

For the moment though, I'll leave this open.

**Comment by aterenin** [comment]
@vabor112 Do you mind re-pulling the latest version from Overleaf, to triple-100%-check that we're submitting the exact same version as just landed on arXiv?

**Comment by vabor112** [comment]
> @vabor112 Do you mind re-pulling the latest version from Overleaf, to triple-100%-check that we're submitting the exact same version as just landed on arXiv?

Done, the only difference was an additional \toprule in a table.

**Comment by krikamol** [comment]
Re. the update after the camera-ready deadline, the committee has briefly discussed. More instructions will follow.

**Review by krikamol — APPROVED** [review]

**Review by krikamol — APPROVED** [review]

**Pull request merged**
